apiVersion: v1
kind: Pod
metadata:
  name: nginx-new
spec:
  containers:
    - name: app
      image: nginx
      resources:
        requests:
          memory: "1500Mi"
          cpu: "50m"
        limits:
          memory: "1800Mi"
          cpu: "200m"

