apiVersion: v1
kind: Pod
metadata:
  name: nginx-01
spec:
  containers:
    - name: nginx
      image: nginx:1.14.2
  nodeSelector:
    groupType: default
---
apiVersion: v1
kind: Pod
metadata:
  name: nginx-01-2
spec:
  containers:
    - name: nginx
      image: nginx:1.14.2
---
apiVersion: v1
kind: Pod
metadata:
  name: nginx-01-3
spec:
  containers:
    - name: nginx
      image: nginx:1.14.2
