apiVersion: v1
kind: Pod
metadata:
  name: nginx-s1
  labels:
    security: S1
spec:
  nodeSelector:
    choice: one
  containers:
    - name: nginx
      image: nginx
---
apiVersion: v1
kind: Pod
metadata:
  name: nginx-s2
  labels:
    security: S2
spec:
  nodeSelector:
    choice: two
  containers:
    - name: nginx
      image: nginx
---
apiVersion: v1
kind: Pod
metadata:
  name: with-pod-affinity
spec:
  affinity:
    podAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchExpressions:
              - key: security
                operator: In
                values:
                  - S2
          topologyKey: choice
  containers:
    - name: nginx
      image: nginx
---
---
apiVersion: v1
kind: Pod
metadata:
  name: with-pod-affinity1
spec:
  affinity:
    podAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchExpressions:
              - key: security
                operator: In
                values:
                  - S2
          topologyKey: choice
  containers:
    - name: nginx
      image: nginx

