apiVersion: v1
kind: Pod
metadata:
  name: nginx
spec:
  containers:
    - name: nginx
      image: nginx:1.14.2

---
apiVersion: v1
kind: Pod
metadata:
  name: webapplication
spec:
  containers:
    - name: webapp1
      image: nginx:1.14.2
    - name: debug
      image: rkalluru/learnk8s:rhel9-bare