apiVersion: v1
kind: Pod
metadata:
  name: nginx
spec:
  containers:
    - name: nginx
      image: nginx:1.14.2
  resources:
    limits:
      cpu: "100m"
      memory: "200Mi"
    requests:
      cpu: "50m"
      memory: "100Mi"