apiVersion: v1
kind: Pod
metadata:
  name: volumes-demo
spec:
  containers:
    - name: nginx
      image: nginx:1.14.2
      volumeMounts:
        - mountPath: /usr/share/nginx/html
          name: html

  volumes:
    - name: html
      emptyDir: {}